# Stage 1: Build the React app
FROM node:current-alpine3.22 AS builder
WORKDIR /app
COPY frontend/myapp/package*.json ./
RUN npm install
COPY frontend/myapp/ .
RUN npm run build

# Stage 2: Serve the build using nginx
FROM nginx:stable-alpine
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 443
CMD ["nginx", "-g", "daemon off;"]
