name: CI/CD React + Node via SSH

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Optional: Build frontend Docker image
    - name: Build React Docker Image
      run: docker build -t react-app -f Dockerfile.frontend ./frontend/myapp


    # Optional: Build backend Docker image
    - name: Build Node Docker Image
      run: docker build -t node-backend -f Dockerfile.backend ./backend

    # Setup SSH key
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    # Copy project files to the server using rsync over SSH
    - name: Copy files to server
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" \
          --exclude=".git" \
          --exclude="node_modules" \
          ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}/app

    # Run Docker Compose on the server
    - name: Run Docker Compose remotely
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd /home/${{ secrets.SSH_USER }}/app
          docker compose -f docker-compose.yml up -d --build
        EOF
